=== Reiswaffl/Kalendar/Calendar/out/resources/CalML.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT calendar (users*,permAppointments*,user*, currentUser*)>
        <!ELEMENT currentUser (#PCDATA)>
        <!ATTLIST currentUser
                id CDATA #REQUIRED>
        <!ELEMENT users (User*)>
        <!ELEMENT User (permAppointment*)>
        <!ATTLIST User
                id CDATA #REQUIRED>
        <!ELEMENT permAppointments (User*)>
        <!ELEMENT permAppointment (#PCDATA)>
        <!ATTLIST permAppointment
                start CDATA #REQUIRED
                end CDATA #REQUIRED
                repetition CDATA #REQUIRED
                weekday CDATA #REQUIRED>
        <!ELEMENT user (years*)>
        <!ATTLIST user
                id CDATA #REQUIRED>
        <!ELEMENT years (month*)>
        <!ATTLIST years
                id CDATA #REQUIRED>
        <!ELEMENT month (day*)>
        <!ATTLIST month
                id CDATA #REQUIRED>
        <!ELEMENT day (period*)>
        <!ATTLIST day
                date CDATA #REQUIRED
                blocked CDATA #REQUIRED>
        <!ELEMENT period (#PCDATA)>
        <!ATTLIST period
                start CDATA #REQUIRED
                end CDATA #REQUIRED
                isfamEvent CDATA #REQUIRED>

=== Reiswaffl/Kalendar/Calendar/out/resources/calendar.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE calendar SYSTEM "CalML.dtd">

<calendar>
    <users>
        <User id="Eric"/>
        <User id="Tom"/>
    </users>
    <currentUser id="Tom"/>

    <permAppointments><User id="Eric">

    </User>
        <User id="Tom">
            <permAppointment end="13:30" repetition="WEEKLY" start="12:30" weekday="TUESDAY">Hier steht meine Werbung</permAppointment>
            <permAppointment end="08:45" repetition="WEEKLY" start="08:00" weekday="MONDAY">Schule:Englisch</permAppointment>
            <permAppointment end="09:30" repetition="WEEKLY" start="08:45" weekday="MONDAY">Schule:Englisch</permAppointment>
            <permAppointment end="10:30" repetition="WEEKLY" start="09:45" weekday="MONDAY">Schule:Geschichte</permAppointment>
            <permAppointment end="11:15" repetition="WEEKLY" start="10:30" weekday="MONDAY">Schule:Geschichte</permAppointment>
            <permAppointment end="12:20" repetition="WEEKLY" start="11:35" weekday="MONDAY">Schule:Informatik</permAppointment>
            <permAppointment end="13:05" repetition="WEEKLY" start="12:20" weekday="MONDAY">Schule:Physik</permAppointment>
            <permAppointment end="14:45" repetition="WEEKLY" start="14:00" weekday="MONDAY">Schule:Seminar</permAppointment>
            <permAppointment end="15:30" repetition="WEEKLY" start="14:45" weekday="MONDAY">Schule:Seminar</permAppointment>
            <permAppointment end="16:15" repetition="WEEKLY" start="15:30" weekday="MONDAY">Schule:Seminar</permAppointment>
            <permAppointment end="17:00" repetition="WEEKLY" start="16:15" weekday="MONDAY">Schule:Seminar</permAppointment>
            <permAppointment end="08:45" repetition="WEEKLY" start="08:00" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="09:30" repetition="WEEKLY" start="08:45" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="10:30" repetition="WEEKLY" start="09:45" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="11:15" repetition="WEEKLY" start="10:30" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="12:20" repetition="WEEKLY" start="11:35" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="13:05" repetition="WEEKLY" start="12:20" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="14:00" repetition="WEEKLY" start="13:15" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="14:45" repetition="WEEKLY" start="14:00" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="15:30" repetition="WEEKLY" start="14:45" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="16:15" repetition="WEEKLY" start="15:30" weekday="MONDAY">Schule:Info</permAppointment>
            <permAppointment end="17:00" repetition="WEEKLY" start="16:15" weekday="MONDAY">Schule:Info</permAppointment>
        </User>
    </permAppointments>
    <user id="Eric">
    </user>
    <user id="Tom">
        <years id="18">
            <month id="02" >
                <day  date="180201"  blocked="false">
                    <period end="14:40" isfamEvent="false" start="13:30">Meine Werbung</period>
                </day>
            </month>
        </years>
    </user>
</calendar>
